Contactlists, Emails and Newsletter endpoints
pionl/smart-emailing-v3 pull request #7
Opened 2020-05-10 14:02 UTC by PavelJurasek

2020-05-28 08:32 UTC, stanislav-janu requested changes
Bylo by možné používat sekci "use" na začátcích dokumentů a v rámci scriptu pak nepoužívat plné cesty k třídám?

2020-06-21 20:58 UTC, pionl commented
Souhlas -- potřebujeme podporovat 7.2 a níže?

2020-06-22 08:13 UTC, stanislav-janu commented
Osobně si myslím, že max 7.1.

2020-06-22 09:05 UTC, pionl commented
škoda, že packagist nemá statistiky použití s PHP verzí :) Já osobně už nepoužívám (projekt byl ukončen). Jenom teda bude potřeba PR upravit.

2020-06-22 09:11 UTC, PavelJurasek commented
Podpora 7.2 končí letos https://www.php.net/supported-versions.php, takže za mě 7.3+

2020-06-22 10:24 UTC, stanislav-janu commented
Myslím, že balíčky by měly mít podporu verzí delší než samotné PHP. Ale vzhledem k tomu, že je relativně jednoduché migrovat na novější verze v rámci 7.X, tak bych souhlasil s podporou 7.3+.

2020-06-22 18:22 UTC, pionl commented
Souhlas (původně balíček byl na 5.6 :))

2020-06-23 15:42 UTC, PavelJurasek commented
Předěláno na 7.3+ a všude jsou use stmt namísto FQN

2020-06-23 18:29 UTC, pionl commented on composer.json
> +        "php": ">=7.3",
Můžeme prosím dát do README nahoru 7.3+ (0.1.8 je poslední verze s podporou 5.6+)

2020-06-23 18:30 UTC, pionl approved these changes

2020-06-23 18:35 UTC, pionl commented
Jinak psr-12 navrhuje  psát `declare(strict_types=1);` na novém řádku než je to nyní

```php
<?php

declare(strict_types=1);

```

2020-06-23 19:33 UTC, pionl commented on composer.json
> +        "php": ">=7.3",
Děkuji

2020-06-27 21:26 UTC, pionl commented
@stanislav-janu je to takto v pořádku? děkuji

2020-06-29 08:27 UTC, stanislav-janu commented
To už vypadá přehledně :-) Nezkoušel jsem funkčnost.
Osobně to deklarování striktnosti taky píšu na novém řádku stejně jako v Nette.
Možná bychom mohli zavést i code standard.

2020-06-29 08:28 UTC, stanislav-janu approved these changes

2020-07-01 08:25 UTC, merged

2020-07-01 08:26 UTC, pionl commented
Díky všem -- releasnuto. 🚀

https://github.com/pionl/smart-emailing-v3/releases/tag/v0.2.0

@stanislav-janu souhlas, něco pak později můžu nastřelit.